server:
  port: 8080

spring:
  application:
    name: demo
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/test
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      
